### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'maker\firebase\google-services.json'

### ISSUE THREAD

**Issue by madan712** [mateuszpijanowski/maker#11]
I downloaded the code and installed it. While running i am getting below error

Error: ENOENT: no such file or directory, open 'maker\firebase\google-services.json'

**Comment by mateuszpijanowski** [comment]
Remove `"googleServicesFile": "./firebase/GoogleService-Info.plist"`, and `"googleServicesFile": "./firebase/google-services.json"` from app.json.
