### ISSUE TITLE
IOS PROBLEM: Invariant Violation: Invariant Violation: [....

### ISSUE THREAD

**Issue by theOigen** [mateuszpijanowski/maker#5]
After installing on iOS simulator I see this error:

Invariant Violation: Invariant Violation: [177,"RCTView",1,{"height":56,"width":56,"borderRadius":28,"backgroundColor":4294185791,"shadowColor":4278190080,"shadowOpacity":0.3,"shadowRadius":"<<NaN>>","shadowOffset":{"height":1,"width":0},"zIndex":1}] is not usable as a native method argument

This error is located at:
    in RCTView (at View.js:45)
    in View (at ActionButton.react.js:337)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at ActionButton.react.js:464)
    in ActionButton (at withTheme.js:12)
    in ThemedComponent (at TaskList.js:594)
    in RCTView (at View.js:45)
    in View (at TaskList.js:592)
    in RCTView (at View.js:45)
    in View (at TaskList.js:515)
    in TaskList (created by ConnectFunction)
    in ConnectFunction (at ToDo.js:59)
    in tasks (created by SceneComponent)
    in SceneComponent (at SceneMap.tsx:16)
    in RCTView (at View.js:45)
    in View (at SceneView.tsx:92)
    in SceneView (at TabView.tsx:165)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at Pager.tsx:667)
    in PanGestureHandler (at Pager.tsx:659)
    in Pager (at TabView.tsx:126)
    in RCTView (at View.js:45)
    in View (at TabView.tsx:125)
    in TabView (at ToDo.js:50)
    in RCTView (at View.js:45)
    in View (at Template.js:56)
    in Template (created by ConnectFunction)
    in ConnectFunction (at ToDo.js:49)
    in ToDo (created by ConnectFunction)
    in ConnectFunction (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:899)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:93)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.tsx:80)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:971)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.tsx:383)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:379)
    in PanGestureHandler (at StackViewLayout.tsx:372)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:103)
    in RCTView (at View.js:45)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:40)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:429)
    in NavigationContainer (at App.js:59)
    in Provider (at App.js:57)
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

And this one:
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, the componentWillUnmount method, 
    in Icon (at Icon/index.js:79)
    in Icon (at withTheme.js:12)
    in ThemedComponent (at TaskList.js:551)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at TaskList.js:550)
    in RCTView (at View.js:45)
    in View (at TaskList.js:543)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at TouchableOpacity.js:282)
    in TouchableOpacity (at ModalDropdown.js:170)
    in RCTView (at View.js:45)
    in View (at ModalDropdown.js:114)
    in ModalDropdown (at TaskList.js:526)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at CenterElement.react.js:166)
    in TouchableWithoutFeedback (at CenterElement.react.js:165)
    in CenterElement (at withTheme.js:12)
    in ThemedComponent (at Toolbar.react.js:464)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at Toolbar.react.js:450)
    in Toolbar (at withTheme.js:12)
    in ThemedComponent (at TaskList.js:516)
    in RCTView (at View.js:45)
    in View (at TaskList.js:515)
    in TaskList (created by ConnectFunction)
    in ConnectFunction (at ToDo.js:59)
    in tasks (created by SceneComponent)
    in SceneComponent (at SceneMap.tsx:16)
    in RCTView (at View.js:45)
    in View (at SceneView.tsx:92)
    in SceneView (at TabView.tsx:165)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:217)
    in AnimatedComponent (at Pager.tsx:667)
    in PanGestureHandler (at Pager.tsx:659)
    in Pager (at TabView.tsx:126)
    in RCTView (at View.js:45)
    in View (at TabView.tsx:125)
    in TabView (at ToDo.js:50)
    in RCTView (at View.js:45)
    in View (at Template.js:56)
    in Template (created by ConnectFunction)
    in ConnectFunction (at ToDo.js:49)
    in ToDo (created by ConnectFunction)
    in ConnectFunction (at SceneView.js:9)
    in SceneView (at StackViewLayout.tsx:899)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewCard.tsx:93)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at screens.native.js:59)
    in Screen (at StackViewCard.tsx:80)
    in Card (at createPointerEventsContainer.tsx:95)
    in Container (at StackViewLayout.tsx:971)
    in RCTView (at View.js:45)
    in View (at screens.native.js:83)
    in ScreenContainer (at StackViewLayout.tsx:383)
    in RCTView (at View.js:45)
    in View (at createAnimatedComponent.js:151)
    in AnimatedComponent (at StackViewLayout.tsx:379)
    in PanGestureHandler (at StackViewLayout.tsx:372)
    in StackViewLayout (at withOrientation.js:30)
    in withOrientation (at StackView.tsx:103)
    in RCTView (at View.js:45)
    in View (at Transitioner.tsx:267)
    in Transitioner (at StackView.tsx:40)
    in StackView (at createNavigator.js:61)
    in Navigator (at createKeyboardAwareNavigator.js:12)
    in KeyboardAwareNavigator (at createAppContainer.js:429)

**Comment by mateuszpijanowski** [comment]
Thanks for report. Now app is unstable in ios devices and emulators. In january/february we planning publish this app in App Store, then this errors should be fixed.
