### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ugintl** [mateuszpijanowski/maker#8]
I want to build this app? What is its license?

**Comment by mateuszpijanowski** [comment]
It's open source MIT License.

**Comment by ugintl** [comment]
Can you please tell me the procedure for building apk and ios in android studio if it is possible?

**Comment by mateuszpijanowski** [comment]
In this project i'm using Expo and to create apk or ios file you can use expo cli. You can read more about that in Expo docs - https://docs.expo.io/distribution/building-standalone-apps/ 
If you want to handle building process you can use expo eject command.
